MeuMercado/Controllers/RedefinirSenhaController.cs
using MeuMercado.Filters;
using MeuMercado.Models;
using MeuMercado.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MeuMercado.Controllers
{
    [PaginaParaUsuarioDeslogado]
    public class RedefinirSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public RedefinirSenhaController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult NovaSenha(UsuarioModel usuario)
        {
            return View(usuario);
        }
        [HttpPost]
        public IActionResult Redefinir(RedefinirSenhaModel redefinirSenha)
        {
            try
            {
                UsuarioModel usuario = _usuarioRepositorio.BuscarPorEmailELogin(redefinirSenha.Email, redefinirSenha.Login);
                if (usuario == null)
                {
                    TempData["MensagemErro"] = "Login e/ou Email informado incoreto.";
                    return RedirectToAction("Index");
                }
                string novaSenha = usuario.GerarNovaSenha();
                _usuarioRepositorio.RedefinirSenha(usuario);
                UsuarioModel usuarioNovaSenha = new UsuarioModel()
                {
                    Senha = novaSenha,
                };
                return RedirectToAction("NovaSenha", usuarioNovaSenha);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível redefinir sua senha. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

MeuMercado/Views/RedefinirSenha/Index.cshtml
@model RedefinirSenhaModel
@{
    Layout = "_LayoutDeslogado";
    ViewData["Title"] = "Redefinir Senha";
}



<div class="text-center">
    <h1>Redefinição de Senha</h1>
</div>

@if (TempData["MensagemSucesso"] != null)
{
        <div class="alert alert-success" role="alert">
        @TempData["MensagemSucesso"]
        </div>
}
@if (TempData["MensagemErro"] != null)
{
        <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]
        </div>
}

<form asp-controller="RedefinirSenha" asp-action="Redefinir">
    <div class="form-group">
        <label for="email" class="form-label">Endereço de Email:</label>
        <input type="text" class="form-control" asp-for="Email" id="email" placeholder="Digite seu Email..." />
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="form-group">
        <label for="login" class="form-label">Login:</label>
        <input type="text" class="form-control" asp-for="Login" id="login" placeholder="Digite seu Login..." />
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>

MeuMercado/Views/RedefinirSenha/NovaSenha.cshtml
@model UsuarioModel
@{
    Layout = "_LayoutDeslogado";
    ViewData["Title"] = "Nova Senha";
}

<div class="text-center">
    <h1>NOVA SENHA</h1>
</div>
<p>Não compartilhe com ninguém !! Sua nova senha é: @Model.Senha</p>
<a asp-controller="Login" asp-action="Index" class="btn btn-primary">Voltar</a>