MeuMercado/Controllers/AlterarSenhaController.cs
using MeuMercado.Filters;
using MeuMercado.Helper.Interfaces;
using MeuMercado.Models;
using MeuMercado.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MeuMercado.Controllers
{
    [PaginaParaUsuarioLogado]
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AlterarSenhaDoUsuario(AlterarSenhaModel alterarSenha)
        {
            try
            {
                UsuarioModel usuario = _sessao.BuscarSessaoDoUsuario();
                if (usuario.SenhaValida(alterarSenha.SenhaAtual) == true)
                {
                    if (alterarSenha.NovaSenha == alterarSenha.ConfirmarNovaSenha)
                    {
                        usuario.Senha = alterarSenha.NovaSenha;
                        _usuarioRepositorio.AlterarSenha(usuario);
                        TempData["MensagemSucesso"] = "Senha alterada com sucesso !";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["MensagemErro"] = "Os campos 'Nova Senha' e 'Confirmar Nova Senha' não são iguais.";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["MensagemErro"] = "Senha atual informada está incorreta.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar sua senha. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

MeuMercado/Controllers/ProdutoController.cs
using MeuMercado.Filters;
using MeuMercado.Helper.Interfaces;
using MeuMercado.Models;
using MeuMercado.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MeuMercado.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtoRepositorio;
        private readonly INotaFiscalRepositorio _notaFiscalRepositorio;
        private readonly ISessao _sessao;

        public ProdutoController(IProdutoRepositorio produtoRepositorio, ISessao sessao, INotaFiscalRepositorio notaFiscalRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
            _sessao = sessao;
            _notaFiscalRepositorio = notaFiscalRepositorio;
        }
        public IActionResult Index()
        { 
            List<ProdutoModel> produtos = _produtoRepositorio.BuscarTodos();
            return View(produtos);
        }
        [HttpGet]
        public IActionResult Comprar(int id)
        {
            ProdutoModel produto = _produtoRepositorio.BuscarPorId(id);
            if (produto == null)
            {
                TempData["MensagemErro"] = "Não foi possível comprar.";
                return RedirectToAction("Index");
            }
            return View(produto);
        }

        public IActionResult ComprarProduto(ProdutoModel produtoComprar)
        {
            UsuarioModel usuario = _sessao.BuscarSessaoDoUsuario();
            ProdutoModel produto = _produtoRepositorio.BuscarPorId(produtoComprar.Id);
            produto.Quantidade -= produtoComprar.Quantidade;
            _produtoRepositorio.Editar(produto);
            NotaFiscalModel notaFiscal = new NotaFiscalModel()
            {
                Id = 0,
                Valor = produtoComprar.Quantidade * produto.Valor,
                ProdutoId = produto.Id,
                UsuarioId = usuario.Id,
            };
            _notaFiscalRepositorio.Criar(notaFiscal);
            TempData["MensagemSucesso"] = "Produto comprado com sucesso !";
            return RedirectToAction("Index", "NotaFiscal");
        }
    }
}

MeuMercado/Controllers/UsuarioComumController.cs
using MeuMercado.Helper.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MeuMercado.Controllers
{
    public class UsuarioComumController : Controller
    {
        private readonly ISessao _sessao;

        public UsuarioComumController(ISessao sessao)
        {
            _sessao= sessao;
        }
        public IActionResult Sair()
        {
                _sessao.RemoverSessaoDoUsuario();
                return RedirectToAction("Index", "Login");
        }
    }
}

MeuMercado/Controllers/UsuarioController.cs
using MeuMercado.Filters;
using MeuMercado.Helper.Interfaces;
using MeuMercado.Models;
using MeuMercado.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MeuMercado.Controllers
{
    [PaginaParaUsuarioLogadoEAdmin]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public UsuarioController(IUsuarioRepositorio usuariorepositorio, ISessao sessao)
        {
            _sessao = sessao;
            _usuarioRepositorio= usuariorepositorio;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();
            return View(usuarios);
        }

        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
             if (usuario == null)
            {
                TempData["MensagemErro"] = "Não foi possível encontrar o usuário pelo ID.";
                return View("Index");
            }
             EditarUsuarioModel usuarioSemSenha = new EditarUsuarioModel()
             {
                 Id = usuario.Id,
                 Nome = usuario.Nome,
                 Sexo = usuario.Sexo,
                 Perfil = usuario.Perfil,
                 Email = usuario.Email,
                 Login = usuario.Login,
             };
             return View(usuarioSemSenha);
        }

        [HttpGet]
        public IActionResult ExcluirConfirmacao(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            if (usuario == null)
            {
                TempData["MensagemErro"] = "Não foi possível encontrar o usuário pelo ID.";
                return View("Index");
            }
            return View(usuario);
        }
        public IActionResult Sair()
        {
            _sessao.RemoverSessaoDoUsuario();
            return RedirectToAction("Index", "Login");
        }

        //METÓDOS PARA CRIAR, ATUALIZAR E EXCLUIR
        [HttpPost]
        public IActionResult CriarUsuario(CriarUsuarioModel usuarioModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuario = new UsuarioModel()
                    {
                        Id = usuarioModel.Id,
                        Nome = usuarioModel.Nome,
                        Sexo = usuarioModel.Sexo,
                        Perfil = usuarioModel.Perfil,
                        Login = usuarioModel.Login,
                        Email = usuarioModel.Email,
                        Senha = usuarioModel.Senha,
                    };
                    _usuarioRepositorio.Criar(usuario);
                    TempData["MensagemSucesso"] = "Usuário criado com sucesso !";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemErro"] = "Preencha todos os campos !";
                    return View("Criar", usuarioModel);
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível criar o seu usuário. Detalhe do erro: {erro.Message}";
                return View("Index");
            }
        }

        [HttpPost]
        public IActionResult Atualizar(EditarUsuarioModel usuarioSemSenha)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuario = new UsuarioModel()
                    {
                        Id = usuarioSemSenha.Id,
                        Nome = usuarioSemSenha.Nome,
                        Sexo = usuarioSemSenha.Sexo,
                        Perfil = usuarioSemSenha.Perfil,
                        Login = usuarioSemSenha.Login,
                        Email = usuarioSemSenha.Email,
                    };
                    _usuarioRepositorio.Editar(usuario);
                    TempData["MensagemSucesso"] = "Usuário atualizado com sucesso !";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemErro"] = "Preencha todos os campos !";
                    return View("Editar");
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível atualizar o seu usuário. Detalhe do erro: {erro.Message}";
                return View("Index");
            }
        }
        public IActionResult Excluir(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            if (usuario == null)
            {
                TempData["MensagemErro"] = "Não foi possível excluir o seu Usuário.";
                return RedirectToAction("Index");
            }
            _usuarioRepositorio.Excluir(usuario);
            TempData["MensagemSucesso"] = "Usuário excluído com sucesso !";
            return RedirectToAction("Index");
        }
    }
}

MeuMercado/Views/Shared/Components/Menu/Default.cshtml
@model UsuarioModel 



<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeuMercado</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-brand nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

        @if (Model.Perfil == MeuMercado.Enums.PerfilEnum.Admin)
        {
                <li class="navbar-brand nav-item">
                    <a class="nav-link text-dark" asp-controller="Usuario" asp-action="Index">Usuários</a>
                </li>
        }
                        <li class="navbar-brand nav-item">
                            <a class="nav-link text-dark" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>

        @if (Model.Perfil == MeuMercado.Enums.PerfilEnum.Admin || Model.Perfil == MeuMercado.Enums.PerfilEnum.Vendedor)
        {
                <li class="navbar-brand nav-item">
                    <a class="nav-link text-dark" asp-controller="UsuarioVendedor" asp-action="MeusProdutos">Meus Produtos</a>
                </li>
        }

        <li class="navbar-brand nav-item">
            <a class="nav-link text-dark" asp-controller="NotaFiscal" asp-action="Index">Minhas Compras</a>
        </li>
        <li class="navbar-brand nav-item">
            <a class="nav-link text-dark" asp-controller="AlterarSenha" asp-action="Index">Alterar Senha</a>
        </li>
        @if (Model.Perfil == MeuMercado.Enums.PerfilEnum.Admin)
        {
                    <li class="navbar-brand nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Sair">Sair</a>
                                </li>
        }
        @if(Model.Perfil == MeuMercado.Enums.PerfilEnum.Vendedor)
        {
                <li class="navbar-brand nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UsuarioVendedor" asp-action="Sair">Sair</a>
                            </li>
        }
        @if(Model.Perfil == MeuMercado.Enums.PerfilEnum.Comum)
        {
            <li class="navbar-brand nav-item">
                <a class="nav-link text-dark" asp-controller="UsuarioComum" asp-action="Sair">Sair</a>
            </li>
        }
        
        <li class="nav-item">
                            <p class="nav-link text-dark align-items-lg-end" style="text-align:right">Olá, @Model.Nome</p>
                        </li>
                    </ul>
                </div>
            